version: '3.8'

services:
  # app:
  #   build: .
  #   ports:
  #     - "4000:4000"
  #   volumes:
  #     - .:/app
  #   environment:
  #     - DB_HOST=mongodb
  #     - DB_PASSWORD=password
  #     - DB_USER=admin
  #     - DB_PORT=27017
  #   command: air



  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo-data:/data/db
    command: 
        - '--quiet'

volumes:
  mongo-data:
